version: "3.9"

services:

  mssql-source:
    container_name: mssql-source
    mem_limit: 2g # running into memory issues running this locally
    image: wwisql
#    platform: linux
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: yourStrong(!)Password

  mssql-target:
    container_name: mssql-target
    mem_limit: 2g # running into memory issues running this locally
#    platform: linux
    image: wwisql
    ports:
      - "2433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: yourStrong(!)Password
